colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
description = "Open-source libraries for agent-first distributed systems"

enableSearch = true
enableCodeCopy = true

[homepage]
  layout = "background"
  homepageImage = "img/PSR-B1509-58.jpg"
  showRecent = false
  layoutBackgroundBlur = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showTableOfContents = true
  showRelatedContent = false
  showReadingTime = false
  showWordCount = false

[list]
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = true

[footer]
  showCopyright = false
  showThemeAttribution = false
